#!/bin/bash

function audit_subdomain {
  subdomain=$1
  domain=$2
  record_type=$(dig +short $subdomain.$domain | awk -F " " '{print $2}')
  destination=$(dig +short $subdomain.$domain)
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 0 ]
  then
    audit_subdomain www $1
    audit_subdomain lb-01 $1
    audit_subdomain web-01 $1
    audit_subdomain web-02 $1
else
  audit_subdomain $2 $1
fi

